version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - errcheck
    - staticcheck
    - ineffassign
    - unused
    - gocyclo
    - dupl
    - goconst
    - unconvert
    - misspell
    - gocritic
    - unparam
    - nakedret
    - revive
  disable:
    - gosec
    - prealloc

formatters:
  enable:
    - goimports

issues:
  max-same-issues: 10
